[package]
name = "sleitnick/axis-simple-example"
version = "0.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Axis = "sleitnick/axis@^0.1"
